import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { twMerge } from "tailwind-merge";
import DashboardHeader from "./(sections)/dashboard-header";
import "./globals.css";
import SidebarSection from "./(sections)/sidebar-section";
import React from "react";
import { SheetSidebarProvider } from "./(components)/sheet-sidebar/sheet-sidebar-provider";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={
                    poppins.className + " h-screen w-screen overflow-hidden"
                }
            >
                <SheetSidebarProvider>
                    <div className="flex h-full w-full flex-row overflow-hidden">
                        <SidebarSection />
                        <div className="flex h-full flex-1 flex-col">
                            <DashboardHeader />
                            {/* <div className="w-full flex-1 overflow-y-auto">
                                {children}
                            </div>                             */}
                            {children}
                        </div>
                    </div>
                </SheetSidebarProvider>
            </body>
        </html>
    );
}
